Add deploy to build action
zentrumnawi/solid-frontend pull request #632
Opened 2020-08-03 11:11 UTC by chgad

2020-08-24 12:57 UTC, mkay-sh requested changes
Bis auf die eine Benennung scheint es ja zu laufen.

2020-08-24 12:57 UTC, mkay-sh commented on .github/workflows/build.yml
> +      - name: Deploy geomat-staging
Sollte die Stage nicht eher dive-staging  heißen?

2020-08-24 15:10 UTC, chgad commented on .github/workflows/build.yml
> +      - name: Deploy geomat-staging
Ja tatsächlich. Copy-Paste-Fehler

2020-08-24 15:14 UTC, chgad commented on .github/workflows/build.yml
> +      - name: Deploy geomat-staging
Erledigt.

2020-09-12 09:46 UTC, mkay-sh approved these changes

2020-09-12 09:47 UTC, merged