Privacy/Info content & Styling
zentrumnawi/solid-frontend pull request #752
Opened 2020-12-21 22:35 UTC by sheepyhollow

- Update der 
- Einige Formatierungssachen und Angleichungen zwischen DivE und GeoMat.
- GeoMat wieder auf light theme umgestellt

2020-12-21 22:38 UTC, sheepyhollow commented
Nicht ganz sicher, ob das styling in `*.component.scss` richtig gemacht ist.
Die `*.component.ts` waren nicht identisch, das habe ich bereinigt - ich hoffe richtig.

2020-12-21 22:43 UTC, sheepyhollow commented
nx format habe ich laufen lassen - keine Ahnung, warum das wieder failed 🤷 
Es läuft durch, listet auch die geänderten Dateien aber es gibt keine Änderungen, die ich pushen könnte.

2021-01-03 08:54 UTC, mkay-sh commented
> nx format habe ich laufen lassen - keine Ahnung, warum das wieder failed 🤷
> Es läuft durch, listet auch die geänderten Dateien aber es gibt keine Änderungen, die ich pushen könnte.

Kann es sein das dein VSCode oder welchen Editor auch immer nach dem Befehl die Änderungen zurückschreibt weil der selber eigene Meinungen zu Formaten hat?

2021-01-03 09:02 UTC, mkay-sh requested changes
Die Formatprobleme müssten noch behoben werden.

2021-01-03 09:02 UTC, mkay-sh commented on apps/geomat/src/app/info-page-content/info-page-content.component.html
> +  Von den Fotos der virtuellen Sammlung über die Gestaltung der Fachinhalte# bis
Soll das `#` da stehen?

2021-01-03 23:00 UTC, sheepyhollow commented on apps/dive/src/app/info-page-content/info-page-content.component.html
> +  <a class="info-link" href="https://github.com/zentrumnawi">Github</a>
yup.

2021-01-03 23:00 UTC, sheepyhollow commented on apps/geomat/src/app/info-page-content/info-page-content.component.html
> +  Von den Fotos der virtuellen Sammlung über die Gestaltung der Fachinhalte# bis
nope.

2021-01-03 23:00 UTC, sheepyhollow commented
Kann es daran liegen? Ich weiß nicht, wie ich das troubleshooten soll. Ich finde quasi keine Doku zu `nx format`
```
$ nx format --base=origin/dev --verbose
warning: LF will be replaced by CRLF in apps/dive/src/app/info-page-content/info-page-content.component.html.
The file will have its original line endings in your working directory
```

2021-01-03 23:22 UTC, sheepyhollow commented
Kann es das hier sein?
https://stackoverflow.com/questions/55245974/prettier-vs-nx-formatcheck
Ich habe eine Prettier-Erweiterung global installiert mit Version 2.2.0 während in unserer `package.json` Version 2.0.5 angegeben ist.

2021-01-12 12:00 UTC, mkay-sh commented
Das ist wirklich seltsam, bei mir lokal läuft das ohne Probleme...

2021-02-16 19:37 UTC, closed without merging